### ISSUE TITLE
[Update] There is 8px of margin in body tag

### ISSUE THREAD

**Issue by soonki-98** [modern-agile-team/dev-portfolio-app#5]
## Description
> ![image](https://user-images.githubusercontent.com/63432381/177579053-5cfd5b21-6f8a-4d20-9170-44ebadff135f.png)

## Progress
- [ ] remove margin located in body

**Comment by seohyunsim** [comment]
이슈 이제 확인했네요 이슈 있는지도 모르고 pr 리뷰남겼네요 하하^^;;

어쩐지 헤더부분이 좀 붕뜨는 이슈가 있던데 이거였군요 이슈 해결 좋아요 👍
